version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  php56:
    build: ./php56
    ports:
      - "80:80"
    working_dir: /var/www/project/foundation
    links:
      - db:db
      
  # php71:
  #   build: ./php71
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./src:/var/www/ServiceViewer/src
  #   working_dir: /var/www/ServiceViewer/src
  #   links:
  #     - db:db

volumes:
  db_data:
